// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatToCook.DAL.Data;

#nullable disable

namespace WhatToCook.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WhatToCook.DAL.Entities.FavoriteRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteRecipes");
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/4197447/pexels-photo-4197447.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/773253/pexels-photo-773253.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Potato"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/4198937/pexels-photo-4198937.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/618775/pexels-photo-618775.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 0,
                            Category = "",
                            ImageUrl = "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg?w=200",
                            IsAllergen = false,
                            Name = "Carrot"
                        });
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentTextColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CookingTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMyRecipe")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = "#9F1239",
                            AccentTextColor = "#881337",
                            Category = "Soup",
                            CookingTime = 60,
                            CreatedAt = new DateTime(2026, 5, 9, 20, 0, 56, 616, DateTimeKind.Utc).AddTicks(8293),
                            Description = "Rich Ukrainian beet soup with vegetables, meat and sour cream on top.",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.pexels.com/photos/5774025/pexels-photo-5774025.jpeg?w=600",
                            IsMyRecipe = false,
                            Rating = 4.9m,
                            Servings = 4,
                            Title = "Borscht"
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = "#B45309",
                            AccentTextColor = "#92400E",
                            Category = "Breakfast",
                            CookingTime = 10,
                            CreatedAt = new DateTime(2026, 5, 9, 20, 0, 56, 616, DateTimeKind.Utc).AddTicks(9992),
                            Description = "Fluffy French-style omelette with herbs, cheese and cherry tomatoes.",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.pexels.com/photos/6294248/pexels-photo-6294248.jpeg?w=600",
                            IsMyRecipe = false,
                            Rating = 4.5m,
                            Servings = 1,
                            Title = "Omelette"
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = "#92400E",
                            AccentTextColor = "#78350F",
                            Category = "Pasta",
                            CookingTime = 25,
                            CreatedAt = new DateTime(2026, 5, 9, 20, 0, 56, 616, DateTimeKind.Utc).AddTicks(9997),
                            Description = "Classic Italian pasta with creamy egg sauce, guanciale and Pecorino Romano.",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?w=600",
                            IsMyRecipe = false,
                            Rating = 4.8m,
                            Servings = 2,
                            Title = "Pasta Carbonara"
                        },
                        new
                        {
                            Id = 4,
                            AccentColor = "#14532D",
                            AccentTextColor = "#166534",
                            Category = "Salad",
                            CookingTime = 5,
                            CreatedAt = new DateTime(2026, 5, 9, 20, 0, 56, 617, DateTimeKind.Utc),
                            Description = "Fresh tomatoes, cucumbers, olives and feta with light olive oil dressing.",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg?w=600",
                            IsMyRecipe = false,
                            Rating = 4.6m,
                            Servings = 2,
                            Title = "Greek Salad"
                        },
                        new
                        {
                            Id = 5,
                            AccentColor = "#B45309",
                            AccentTextColor = "#92400E",
                            Category = "Soup",
                            CookingTime = 45,
                            CreatedAt = new DateTime(2026, 5, 9, 20, 0, 56, 617, DateTimeKind.Utc).AddTicks(3),
                            Description = "Warm and comforting homemade chicken soup with vegetables and noodles.",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?w=600",
                            IsMyRecipe = false,
                            Rating = 4.7m,
                            Servings = 4,
                            Title = "Chicken Soup"
                        },
                        new
                        {
                            Id = 6,
                            AccentColor = "#7C2D12",
                            AccentTextColor = "#6B2110",
                            Category = "Meat",
                            CookingTime = 20,
                            CreatedAt = new DateTime(2026, 5, 9, 20, 0, 56, 617, DateTimeKind.Utc).AddTicks(6),
                            Description = "Juicy pan-seared beef steak with garlic butter, rosemary and thyme.",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.pexels.com/photos/618775/pexels-photo-618775.jpeg?w=600",
                            IsMyRecipe = false,
                            Rating = 4.9m,
                            Servings = 2,
                            Title = "Beef Steak"
                        });
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.FavoriteRecipe", b =>
                {
                    b.HasOne("WhatToCook.DAL.Entities.Recipe", "Recipe")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatToCook.DAL.Entities.User", "User")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("WhatToCook.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatToCook.DAL.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.Recipe", b =>
                {
                    b.Navigation("FavoriteRecipes");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("WhatToCook.DAL.Entities.User", b =>
                {
                    b.Navigation("FavoriteRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
